[package]
name = "use_scale_reexport"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scale_reexport = { path = "../scale_reexport" }
